export const FETCH_PRODUCTS_LOADING = 'FETCH_PRODUCTS_LOADING';
export const SET_PRODUCTS_ITEMS = 'SET_PRODUCTS_ITEMS';
export const CHANGE_MENU_ITEM = 'CHANGE_MENU_ITEM';
export const ADD_NEW_CATEGORY = 'ADD_NEW_CATEGORY';
export const ADD_NEW_MENU_ITEM = 'ADD_NEW_MENU_ITEM';
